# Generated by Django 3.2 on 2023-10-17 18:35

import django.core.validators
from django.db import migrations, models
import user.managers


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='myuser',
            managers=[
                ('objects', user.managers.MyUserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='child',
        ),
        migrations.AddField(
            model_name='myuser',
            name='child_first_name',
            field=models.TextField(blank=True, max_length=150, verbose_name='Имя ребенка'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='child_last_name',
            field=models.TextField(blank=True, max_length=150, verbose_name='Фамилия ребенка'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='phone',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Номер должен быть набран в формате "+9(9)9999999".', regex='^\\+\\d{1,3}[\\d()-]{6,14}\\d$')], verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.TextField(blank=True, max_length=150, verbose_name='Username'),
        ),
    ]
