# Generated by Django 3.2 on 2023-10-30 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_myuser_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='child_first_name',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='child_last_name',
        ),
    ]
