# Generated by Django 4.2.6 on 2023-11-02 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewkindergarten',
            options={'verbose_name': 'Отзыв детского сада', 'verbose_name_plural': 'Отзывы детских садов'},
        ),
        migrations.AlterModelOptions(
            name='reviewschool',
            options={'verbose_name': 'Отзыв школы', 'verbose_name_plural': 'Отзывы школ'},
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
