# Generated by Django 3.2 on 2023-11-16 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_auto_20231116_1137'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewkindergarten',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.myuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviewkindergarten',
            name='review_post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='education.kindergartens'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviewschool',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.myuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviewschool',
            name='review_post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='education.school'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='reviewkindergarten',
            constraint=models.UniqueConstraint(fields=('author', 'review_post'), name='unique_author_reviewkindergarten'),
        ),
        migrations.AddConstraint(
            model_name='reviewschool',
            constraint=models.UniqueConstraint(fields=('author', 'review_post'), name='unique_author_reviewschool'),
        ),
    ]
