# Generated by Django 3.2 on 2023-11-16 08:37

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourites_kindergartens',
            name='kindergartens',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='favourites_users', to='education.kindergartens', verbose_name='Детский садик в избранном'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favourites_kindergartens',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='favourites_kindergartens', to='user.myuser', verbose_name='Пользователь'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favourites_school',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='favourites_school', to='user.myuser', verbose_name='Пользователь'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kindergartens',
            name='type',
            field=models.CharField(choices=[('kindergarten', 'Детский сад'), ('school', 'Школа')], default='kindergarten', max_length=13),
        ),
        migrations.AlterField(
            model_name='school',
            name='type',
            field=models.CharField(choices=[('kindergarten', 'Детский сад'), ('school', 'Школа')], default='school', max_length=13),
        ),
        migrations.AlterField(
            model_name='underground',
            name='color',
            field=colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=25, samples=None, verbose_name='Цвет ветки'),
        ),
    ]
