# Generated by Django 4.2.6 on 2023-10-30 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KindergartenAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('image', models.ImageField(upload_to='kindergartens/', verbose_name='фото')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('image', models.ImageField(upload_to='school/', verbose_name='фото')),
            ],
        ),
        migrations.RemoveField(
            model_name='kindergartens',
            name='album',
        ),
        migrations.RemoveField(
            model_name='school',
            name='album',
        ),
        migrations.AddField(
            model_name='kindergartens',
            name='website',
            field=models.URLField(blank=True, null=True, unique=True, verbose_name='Веб-сайт'),
        ),
        migrations.AddField(
            model_name='school',
            name='website',
            field=models.URLField(blank=True, null=True, unique=True, verbose_name='Веб-сайт'),
        ),
        migrations.AlterField(
            model_name='agecategory',
            name='category',
            field=models.CharField(max_length=256, verbose_name='Возрастная категория'),
        ),
        migrations.AlterField(
            model_name='kindergartens',
            name='age_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='education.agecategory', verbose_name='Возрастная категория'),
        ),
        migrations.AlterField(
            model_name='kindergartens',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='education.area', verbose_name='Округ'),
        ),
        migrations.AlterField(
            model_name='kindergartens',
            name='email',
            field=models.EmailField(blank=True, max_length=250, null=True, unique=True, verbose_name='Электронный адрес'),
        ),
        migrations.AlterField(
            model_name='kindergartens',
            name='telephone',
            field=models.CharField(max_length=250, unique=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='school',
            name='age_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='education.agecategory', verbose_name='Возрастная категория'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='school',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='education.area', verbose_name='Округ'),
        ),
        migrations.AlterField(
            model_name='school',
            name='email',
            field=models.EmailField(blank=True, max_length=250, null=True, unique=True, verbose_name='Электронный адрес'),
        ),
        migrations.AlterField(
            model_name='school',
            name='telephone',
            field=models.CharField(max_length=250, unique=True, verbose_name='Телефон'),
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.AddField(
            model_name='schoolalbum',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='album', to='education.school', verbose_name='Школа'),
        ),
        migrations.AddField(
            model_name='kindergartenalbum',
            name='kindergarten',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='album', to='education.kindergartens', verbose_name='Сад'),
        ),
    ]
