# Generated by Django 3.2 on 2023-11-01 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agecategory',
            options={'ordering': ('name',), 'verbose_name': 'Возрастная категория', 'verbose_name_plural': 'Возрастные категории'},
        ),
        migrations.RemoveField(
            model_name='agecategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='kindergartenalbum',
            name='name',
        ),
        migrations.RemoveField(
            model_name='school',
            name='is_favorited',
        ),
        migrations.RemoveField(
            model_name='schoolalbum',
            name='name',
        ),
        migrations.AddField(
            model_name='agecategory',
            name='name',
            field=models.CharField(default='add', max_length=256, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agecategory',
            name='slug',
            field=models.SlugField(default='add', unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='kindergartens',
            name='create_dev',
        ),
        migrations.AddField(
            model_name='kindergartens',
            name='create_dev',
            field=models.ManyToManyField(blank=True, related_name='kindergartens', to='education.Create', verbose_name='Творческое развитие'),
        ),
        migrations.RemoveField(
            model_name='kindergartens',
            name='intel_dev',
        ),
        migrations.AddField(
            model_name='kindergartens',
            name='intel_dev',
            field=models.ManyToManyField(blank=True, related_name='kindergartens', to='education.Intelligence', verbose_name='Интеллектуальное развитие'),
        ),
        migrations.RemoveField(
            model_name='kindergartens',
            name='music_dev',
        ),
        migrations.AddField(
            model_name='kindergartens',
            name='music_dev',
            field=models.ManyToManyField(blank=True, related_name='kindergartens', to='education.Music', verbose_name='Музыкальное развитие'),
        ),
        migrations.AlterField(
            model_name='kindergartens',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Название детского сада'),
        ),
        migrations.AlterField(
            model_name='kindergartens',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена в месяц'),
        ),
        migrations.AlterField(
            model_name='kindergartens',
            name='price_of_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена в год'),
        ),
        migrations.RemoveField(
            model_name='kindergartens',
            name='sport_dev',
        ),
        migrations.AddField(
            model_name='kindergartens',
            name='sport_dev',
            field=models.ManyToManyField(blank=True, related_name='kindergartens', to='education.Sport', verbose_name='Спортивное развитие'),
        ),
    ]
