# Generated by Django 3.2 on 2023-10-16 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favourites_school',
            old_name='education',
            new_name='school',
        ),
    ]
