# Generated by Django 3.2 on 2023-10-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='underground',
            field=models.ManyToManyField(related_name='course', to='education.Underground', verbose_name='Метро'),
        ),
        migrations.AlterField(
            model_name='kindergartens',
            name='underground',
            field=models.ManyToManyField(related_name='kindergartens', to='education.Underground', verbose_name='Метро'),
        ),
        migrations.AlterField(
            model_name='school',
            name='underground',
            field=models.ManyToManyField(related_name='school', to='education.Underground', verbose_name='Метро'),
        ),
    ]
