# Generated by Django 3.2 on 2023-11-09 08:15

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kindergartens',
            old_name='group_suze',
            new_name='group_size',
        ),
        migrations.RemoveField(
            model_name='kindergartens',
            name='development',
        ),
        migrations.AddField(
            model_name='kindergartens',
            name='create_dev',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Творческое развитие'),
        ),
        migrations.AddField(
            model_name='kindergartens',
            name='intel_dev',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Интеллектуальное развитие'),
        ),
        migrations.AddField(
            model_name='kindergartens',
            name='music_dev',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Музыкальное развитие'),
        ),
        migrations.AddField(
            model_name='kindergartens',
            name='sport_dev',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Спортивное развитие'),
        ),
        migrations.AlterField(
            model_name='kindergartens',
            name='age_category',
            field=models.ManyToManyField(blank=True, to='education.AgeCategory', verbose_name='Возрастная категория'),
        ),
        migrations.AlterField(
            model_name='underground',
            name='color',
            field=colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=25, samples=None, verbose_name='Цвет ветки'),
        ),
        migrations.DeleteModel(
            name='Development',
        ),
    ]
