# Generated by Django 3.2 on 2023-11-09 15:16

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_auto_20231109_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='underground',
            name='color',
            field=colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=18, samples=None, verbose_name='Цвет ветки'),
        ),
    ]
