# Generated by Django 3.2 on 2023-11-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_underground_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Класс в школе',
                'verbose_name_plural': 'Классы в школе',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Время работы',
                'verbose_name_plural': 'Время работы',
                'ordering': ('name',),
            },
        ),
        migrations.RemoveField(
            model_name='kindergartens',
            name='age',
        ),
        migrations.RemoveField(
            model_name='school',
            name='age',
        ),
        migrations.AddField(
            model_name='kindergartens',
            name='preparing_for_school',
            field=models.BooleanField(default=False, verbose_name='Подготовка к школе'),
        ),
        migrations.RemoveField(
            model_name='kindergartens',
            name='age_category',
        ),
        migrations.AddField(
            model_name='kindergartens',
            name='age_category',
            field=models.ManyToManyField(blank=True, null=True, to='education.AgeCategory', verbose_name='Возрастная категория'),
        ),
        migrations.RemoveField(
            model_name='kindergartens',
            name='working_hours',
        ),
        migrations.RemoveField(
            model_name='school',
            name='classes',
        ),
        migrations.AddField(
            model_name='kindergartens',
            name='working_hours',
            field=models.ManyToManyField(blank=True, related_name='kindergartens', to='education.WorkingHours', verbose_name='Языки'),
        ),
        migrations.AddField(
            model_name='school',
            name='classes',
            field=models.ManyToManyField(blank=True, related_name='school', to='education.Class', verbose_name='Классы'),
        ),
    ]
