# Generated by Django 3.2 on 2023-11-19 19:30

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_auto_20231116_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='kindergartens',
            name='coordinates',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Координаты'),
        ),
        migrations.AddField(
            model_name='school',
            name='coordinates',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Координаты'),
        ),
        migrations.AlterField(
            model_name='underground',
            name='color',
            field=colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=18, samples=None, verbose_name='Цвет ветки'),
        ),
    ]
