# Generated by Django 3.2 on 2023-11-15 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kindergartens',
            name='type',
            field=models.CharField(choices=[('kindergarten', 'Детский сад'), ('school', 'Школа')], default='kindergarten', max_length=13),
        ),
        migrations.AlterField(
            model_name='school',
            name='type',
            field=models.CharField(choices=[('kindergarten', 'Детский сад'), ('school', 'Школа')], default='school', max_length=13),
        ),
    ]
