# Generated by Django 4.2.6 on 2023-10-31 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_kindergartenalbum_schoolalbum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='is_favorited',
            field=models.BooleanField(default=False, verbose_name='В избранном'),
        ),
    ]
