# Generated by Django 3.2 on 2023-10-16 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('education', '0002_rename_education_favourites_school_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название школы')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('album', models.ImageField(upload_to='education/', verbose_name='Изображение')),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='RU')),
                ('address', models.CharField(max_length=250, verbose_name='Адрес')),
                ('email', models.EmailField(max_length=250, verbose_name='Электронный адрес')),
                ('underground', models.CharField(max_length=250, verbose_name='Метро')),
                ('area', models.CharField(max_length=250, verbose_name='Округ')),
                ('price', models.PositiveSmallIntegerField(verbose_name='Цена в месяц')),
                ('age', models.CharField(max_length=250, verbose_name='Возраст')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Create',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Творческое занятие',
                'verbose_name_plural': 'Творческие занятия',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Intelligence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Интеллектуальное занятие',
                'verbose_name_plural': 'Интеллектуальные занятия',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Музыкальное занятие',
                'verbose_name_plural': 'Музыкальные занятия',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Спортивное занятие',
                'verbose_name_plural': 'Спортивные занятия',
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='favourites_school',
            options={'verbose_name': 'Избранное - школа', 'verbose_name_plural': 'Избранное - школы'},
        ),
        migrations.AlterField(
            model_name='favourites_school',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites_school', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Название'),
        ),
        migrations.CreateModel(
            name='Kindergartens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название школы')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('album', models.ImageField(upload_to='education/', verbose_name='Изображение')),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='RU')),
                ('address', models.CharField(max_length=250, verbose_name='Адрес')),
                ('email', models.EmailField(max_length=250, verbose_name='Электронный адрес')),
                ('underground', models.CharField(max_length=250, verbose_name='Метро')),
                ('area', models.CharField(max_length=250, verbose_name='Округ')),
                ('price', models.PositiveSmallIntegerField(verbose_name='Цена в месяц')),
                ('age', models.CharField(max_length=250, verbose_name='Возраст')),
                ('price_of_year', models.PositiveSmallIntegerField(verbose_name='Цена в год')),
                ('working_hours', models.CharField(max_length=250, verbose_name='Время работы')),
                ('group_suze', models.CharField(max_length=250, verbose_name='Размер группы')),
                ('create_dev', models.ManyToManyField(related_name='kindergartens', to='education.Create', verbose_name='Творческое развитие')),
                ('intel_dev', models.ManyToManyField(related_name='kindergartens', to='education.Intelligence', verbose_name='Интеллектуальное развитие')),
                ('languages', models.ManyToManyField(related_name='kindergartens', to='education.Language', verbose_name='Иностранные языки')),
                ('music_dev', models.ManyToManyField(related_name='kindergartens', to='education.Music', verbose_name='Музыкальное развитие')),
                ('sport_dev', models.ManyToManyField(related_name='kindergartens', to='education.Sport', verbose_name='Спортивное развитие')),
            ],
            options={
                'verbose_name': 'Детский сад',
                'verbose_name_plural': 'Детские сады',
            },
        ),
        migrations.CreateModel(
            name='Favourites_Kindergartens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kindergartens', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites_users', to='education.kindergartens', verbose_name='Детский садик в избранном')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites_kindergartens', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Избранное - детский садик',
                'verbose_name_plural': 'Избранное - детские сады',
            },
        ),
        migrations.CreateModel(
            name='Favourites_Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites_users', to='education.course', verbose_name='Курс в избранном')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites_course', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Избранное - курс',
                'verbose_name_plural': 'Избранное - курсы',
            },
        ),
    ]
