# Generated by Django 4.2.6 on 2023-10-31 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_school_is_favorited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='is_favorited',
        ),
    ]
