# Generated by Django 3.2 on 2023-11-09 18:24

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_alter_underground_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='underground',
            name='color',
            field=colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=25, samples=None, verbose_name='Цвет ветки'),
        ),
    ]
