# Generated by Django 3.2 on 2023-10-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_auto_20231018_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='languages',
        ),
        migrations.AddField(
            model_name='school',
            name='languages',
            field=models.CharField(default='нужно заполнить', max_length=250, verbose_name='Языки'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='school',
            name='profile',
        ),
        migrations.AddField(
            model_name='school',
            name='profile',
            field=models.CharField(default='нужно заполнить', max_length=250, verbose_name='Профиль'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='school',
            name='underground',
        ),
        migrations.AddField(
            model_name='school',
            name='underground',
            field=models.CharField(default='нужно заполнить', max_length=250, verbose_name='Метро'),
            preserve_default=False,
        ),
    ]
