# Generated by Django 3.2 on 2023-11-14 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_alter_underground_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favourites_kindergartens',
            options={'ordering': ('user',), 'verbose_name': 'Избранное - детский садик', 'verbose_name_plural': 'Избранное - детские сады'},
        ),
        migrations.AlterModelOptions(
            name='favourites_school',
            options={'ordering': ('user',), 'verbose_name': 'Избранное - школа', 'verbose_name_plural': 'Избранное - школы'},
        ),
        migrations.AlterModelOptions(
            name='kindergartens',
            options={'ordering': ('name',), 'verbose_name': 'Детский сад', 'verbose_name_plural': 'Детские сады'},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ('name',), 'verbose_name': 'Школа', 'verbose_name_plural': 'Школы'},
        ),
        migrations.CreateModel(
            name='SchoolAverageRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_rating', models.FloatField(blank=True, default=None, null=True, verbose_name='Средняя оценка')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.school')),
            ],
            options={
                'verbose_name': 'Средняя оценка школы',
                'verbose_name_plural': 'Средние оценки школ',
            },
        ),
        migrations.CreateModel(
            name='KindergartenAverageRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_rating', models.FloatField(blank=True, default=None, null=True, verbose_name='Средняя оценка')),
                ('kindergarten', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.kindergartens')),
            ],
            options={
                'verbose_name': 'Средняя оценка детского сада',
                'verbose_name_plural': 'Средние оценки детских садов',
            },
        ),
    ]
