# Generated by Django 3.2 on 2023-11-19 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_auto_20231119_2230'),
        ('education', '0004_auto_20231119_2228'),
    ]

    operations = [
    ]
