# Generated by Django 3.2 on 2023-10-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_auto_20231018_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='working_hours',
            field=models.CharField(default='add', max_length=250, verbose_name='Время работы'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='album',
            field=models.ImageField(upload_to='course/', verbose_name='Изображение'),
        ),
        migrations.RemoveField(
            model_name='course',
            name='underground',
        ),
        migrations.AddField(
            model_name='course',
            name='underground',
            field=models.CharField(default='add', max_length=250, verbose_name='Метро'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='kindergartens',
            name='album',
        ),
        migrations.AddField(
            model_name='kindergartens',
            name='album',
            field=models.ManyToManyField(related_name='kindergartens', to='education.Album', verbose_name='фото'),
        ),
        migrations.RemoveField(
            model_name='kindergartens',
            name='create_dev',
        ),
        migrations.AddField(
            model_name='kindergartens',
            name='create_dev',
            field=models.CharField(default='add', max_length=250, verbose_name='Творческое развитие'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='kindergartens',
            name='intel_dev',
        ),
        migrations.AddField(
            model_name='kindergartens',
            name='intel_dev',
            field=models.CharField(default='add', max_length=250, verbose_name='Интеллектуальное развитие'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='kindergartens',
            name='languages',
        ),
        migrations.AddField(
            model_name='kindergartens',
            name='languages',
            field=models.CharField(default='add', max_length=250, verbose_name='Языки'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='kindergartens',
            name='music_dev',
        ),
        migrations.AddField(
            model_name='kindergartens',
            name='music_dev',
            field=models.CharField(default='add', max_length=250, verbose_name='Музыкальное развитие'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='kindergartens',
            name='sport_dev',
        ),
        migrations.AddField(
            model_name='kindergartens',
            name='sport_dev',
            field=models.CharField(default='add', max_length=250, verbose_name='Спортивное развитие'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='kindergartens',
            name='underground',
        ),
        migrations.AddField(
            model_name='kindergartens',
            name='underground',
            field=models.CharField(default='add', max_length=250, verbose_name='Метро'),
            preserve_default=False,
        ),
    ]
