# Generated by Django 3.2 on 2023-10-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_auto_20231019_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='album',
        ),
        migrations.AddField(
            model_name='course',
            name='album',
            field=models.ManyToManyField(related_name='course', to='education.Album', verbose_name='фото'),
        ),
    ]
