# Generated by Django 3.2 on 2023-11-19 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_merge_0003_auto_20231119_2230_0004_auto_20231119_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kindergartens',
            name='coordinates',
        ),
        migrations.RemoveField(
            model_name='kindergartens',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='kindergartens',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='school',
            name='coordinates',
        ),
    ]
