# Generated by Django 3.2 on 2023-11-20 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_merge_0003_auto_20231119_2230_0004_auto_20231119_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kindergartens',
            name='coordinates',
        ),
        migrations.RemoveField(
            model_name='school',
            name='coordinates',
        ),
        migrations.AlterField(
            model_name='kindergartens',
            name='latitude',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='kindergartens',
            name='longitude',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
