# Generated by Django 3.2 on 2023-10-19 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0006_auto_20231019_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='album',
        ),
        migrations.CreateModel(
            name='CourseAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('image', models.ImageField(upload_to='course/', verbose_name='фото')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album', to='education.course', verbose_name='Курсы')),
            ],
        ),
    ]
