# Generated by Django 4.2.6 on 2023-10-31 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0006_remove_school_is_favorited'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='is_favorited',
            field=models.BooleanField(default=False),
        ),
    ]
