# Generated by Django 3.2 on 2023-11-19 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0006_auto_20231119_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='school',
            name='longitude',
        ),
    ]
