# Generated by Django 4.2.6 on 2023-10-29 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0007_auto_20231020_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursealbum',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='album', to='education.course', verbose_name='Курсы'),
        ),
    ]
