# Generated by Django 3.2 on 2023-10-31 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0007_school_is_favorited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='is_favorited',
            field=models.BooleanField(default=False, verbose_name='В избранном'),
        ),
    ]
