# Generated by Django 4.2.6 on 2023-10-31 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0008_alter_school_is_favorited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='name_author',
        ),
        migrations.AlterField(
            model_name='school',
            name='age_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='education.agecategory', verbose_name='Возрастная категория'),
        ),
        migrations.AlterField(
            model_name='school',
            name='is_favorited',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='В избранном'),
        ),
    ]
