# Generated by Django 4.2.6 on 2023-10-29 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0009_agecategory_area_kindergartens_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kindergartens',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='school',
            name='profile',
        ),
        migrations.AddField(
            model_name='school',
            name='profile',
            field=models.ManyToManyField(related_name='school', to='education.profile', verbose_name='Профиль'),
        ),
    ]
