# Generated by Django 4.2.6 on 2023-10-29 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0010_remove_kindergartens_profile_remove_school_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kindergartens',
            name='underground',
        ),
        migrations.RemoveField(
            model_name='school',
            name='underground',
        ),
        migrations.AddField(
            model_name='kindergartens',
            name='underground',
            field=models.ManyToManyField(related_name='kindergartens', to='education.underground', verbose_name='Метро'),
        ),
        migrations.AddField(
            model_name='school',
            name='underground',
            field=models.ManyToManyField(related_name='school', to='education.underground', verbose_name='Метро'),
        ),
    ]
