# Generated by Django 4.2.6 on 2023-10-29 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0011_remove_kindergartens_underground_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agecategory',
            name='category',
            field=models.CharField(blank=True, choices=[('Дошкольное обучение', 'Дошкольное обучение'), ('Начальная школа', 'Начальная школа'), ('Основная школа', 'Основная школа'), ('Старшая школа', 'Старшая школа')], max_length=20, null=True, verbose_name='Возрастная категория'),
        ),
        migrations.AlterField(
            model_name='school',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='school',
            name='age',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='school',
            name='age_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='education.agecategory', verbose_name='Возрастная категория'),
        ),
        migrations.AlterField(
            model_name='school',
            name='album',
            field=models.ManyToManyField(blank=True, null=True, related_name='school', to='education.album', verbose_name='фото'),
        ),
        migrations.AlterField(
            model_name='school',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='education.area', verbose_name='Округ'),
        ),
        migrations.AlterField(
            model_name='school',
            name='classes',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Классы'),
        ),
        migrations.AlterField(
            model_name='school',
            name='email',
            field=models.EmailField(blank=True, max_length=250, null=True, verbose_name='Электронный адрес'),
        ),
        migrations.AlterField(
            model_name='school',
            name='languages',
            field=models.ManyToManyField(blank=True, null=True, related_name='school', to='education.language', verbose_name='Языки'),
        ),
        migrations.AlterField(
            model_name='school',
            name='name_author',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Имя автора'),
        ),
        migrations.AlterField(
            model_name='school',
            name='price',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Цена в месяц'),
        ),
        migrations.AlterField(
            model_name='school',
            name='price_of_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Цена в год'),
        ),
        migrations.AlterField(
            model_name='school',
            name='profile',
            field=models.ManyToManyField(blank=True, null=True, related_name='school', to='education.profile', verbose_name='Профиль'),
        ),
        migrations.AlterField(
            model_name='school',
            name='underground',
            field=models.ManyToManyField(blank=True, null=True, related_name='school', to='education.underground', verbose_name='Метро'),
        ),
        migrations.AlterField(
            model_name='school',
            name='working_hours',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Время работы'),
        ),
    ]
