# Generated by Django 4.2.6 on 2023-10-29 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0014_alter_kindergartens_address_alter_kindergartens_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='album',
            field=models.ManyToManyField(blank=True, related_name='course', to='education.album', verbose_name='фото'),
        ),
        migrations.AlterField(
            model_name='course',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='course',
            name='age',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='course',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='education.area', verbose_name='Округ'),
        ),
        migrations.AlterField(
            model_name='course',
            name='email',
            field=models.EmailField(blank=True, max_length=250, null=True, verbose_name='Электронный адрес'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Цена в месяц'),
        ),
        migrations.RemoveField(
            model_name='course',
            name='underground',
        ),
        migrations.DeleteModel(
            name='CourseAlbum',
        ),
        migrations.AddField(
            model_name='course',
            name='underground',
            field=models.ManyToManyField(blank=True, related_name='courses', to='education.underground', verbose_name='Метро'),
        ),
    ]
